default_schema: portal

server:
  port: 9091

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aft_portal
    username: aft_portal_admin
    password: 4321
    test-on-borrow: true
    init-SQL: SET search_path = ${default_schema}
    validation-query: select 1
    test-on-connect: true
    validation-interval: 100000

  jpa:
    generate-ddl: true
    show-sql: false
    formated-sql: false
    hibernate:
      ddl-auto: validate
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    open-in-view: false

    properties:
      hibernate:
        default_schema: ${default_schema}
        jdbc:
          batch_size: 30
          order_inserts: true
          order_updates: true
          batch_versioned_data: true
          generate_statistics: true

  thymeleaf:
    cache: true
    mode: HTML
    prefix: classpath:/templates/

  liquibase:
    enabled: false

logging:
  level:
    root: INFO
    liquibase: INFO
  file:
    name: application-web.log
    max-history: 5
    max-size: 50MB
